/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 04 15:14:28 GMT 2024
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Triangle_ESTest extends Triangle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Triangle.triangle(0, (-1914), 1149);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Triangle.triangle(1187, 1187, 1187);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Triangle.triangle(955, 3508, 3508);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Triangle.triangle(955, 1972, 3021);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Triangle.triangle(955, 955, (-90));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Triangle.triangle(955, (-1047), 933);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Triangle.triangle(0, 1536, 0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Triangle.triangle(955, (-1202), (-2861));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Triangle.triangle(1, 5925, (-1896));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Triangle.triangle(955, 3508, (-1500));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Triangle.triangle(1266, 2106, 2);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Triangle.triangle((-131), (-3260), 0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Triangle.triangle((-2082), (-2082), (-634));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Triangle.triangle((-2082), 459, (-3786));
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Triangle.triangle(1, 2, (-1));
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Triangle.triangle(0, 1967, (-1396));
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Triangle.triangle(955, 955, 1686);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Triangle.triangle(955, 1972, 955);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Triangle.triangle(2, (-4979), (-1));
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Triangle.triangle((-131), (-131), (-131));
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Triangle.triangle(1, 1, 1);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Triangle.triangle(0, (-1056), 1522);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Triangle.triangle((-131), 251, (-892));
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Triangle triangle0 = new Triangle();
  }
}
